-- AI work queue. Rows are generated by the generate-work-items edge function
-- (called with the user's JWT, so owner RLS applies) and mutated by the client
-- (approve/dismiss/done). draft holds prose only — amounts live in `amount`,
-- copied from DB aggregates at generation time, never from model output.

create table public.ai_work_items (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  customer_id uuid references public.customers(id) on delete cascade,
  lead_id uuid references public.leads(id) on delete set null,
  order_id uuid references public.orders(id) on delete set null,
  kind text not null check (kind in
    ('reply','payment_reminder','create_order','invoice','follow_up','share_catalog')),
  priority text not null check (priority in ('high','medium','low')),
  score integer not null default 0,
  title text not null,
  context text,
  amount numeric(12,2),
  draft jsonb not null default '{}'::jsonb,
  confidence numeric(3,2),
  status text not null default 'pending'
    check (status in ('pending','approved','dismissed','expired','done')),
  batch_id uuid not null,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger trg_ai_work_items_updated before update on public.ai_work_items
  for each row execute function public.set_updated_at();

create index idx_ai_work_items_queue
  on public.ai_work_items (user_id, status, priority, score desc);

alter table public.ai_work_items enable row level security;

create policy "own ai_work_items" on public.ai_work_items
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
